http:
  host: "![ZC/56rPoX8G4agZ6phMkwA==]"
  port: "![2nmQAmrRPug=]"

database:
  url: "![1Vh7M1Ez2ysEQUQKCN2MccN7MdRTvgIEftmWOurdgdgYjYypp7h+tDvflQGB0RUvo+zZlIxW0I8=]"
  driver: "![xTrukgkH5IwHiJPFGSazmfVuTkfVp9yn]"
  user: "![T9wylRZI5N6cCsU1lcShWg==]"
  password: "![MnIwgSEEwCAWIyBr2++DBKGaQw1mXJ/TNWHEeqV4yEHtGTmWVBA/cA==]"
